###
GET http://localhost:3000/api/apoiadores


###
GET http://localhost:3000/api/apoiadores/5


###
POST http://localhost:3000/api/apoiadores
Content-Type: application/json

{
    "nome": "Ciclano de Tal",
    "apelido": null,
    "dataNascimento": "01/12/2005",
    "email": "ciclanodetal@gmail.com",
    "profissao": "Médico",
    "religiao": "Ateu",
    "endereco": 
        {
            "cidade": 2,
            "bairro": "Residencial Boa Nova",
            "numero": "02",
            "lagradouro": "Avenida 05",
            "quadra": "T",
            "pontoReferencia": null
        },
    "classificacao": 8,
    "situacao": 5,
    "informacaoAdicional": "Fazendo um teste de envio de dados via API"
}


###
PUT http://localhost:3000/api/apoiadores/5
Content-Type: application/json

{
    "nome": "Fulano de Tal Sobrinho",
    "apelido": "Fulaninho",
    "dataNascimento": "01/12/2001",
    "email": "fulanodetal@gmail.com",
    "profissao": "Outros",
    "religiao": "Cotolica",
    "endereco": 
        {
            "cidade": 2,
            "bairro": "Vila Nova",
            "numero": "45",
            "lagradouro": "Rua 16",
            "quadra": "G-16",
            "pontoReferencia": "Ao lado da igreja."
        },
    "classificacao": 10,
    "situacao": 5,
    "informacaoAdicional": "Fazendo um teste de envio de dados via API"
}


###
DELETE http://localhost:3000/api/apoiadores/2

