###
GET http://localhost:3000/api/enderecos



###
POST http://localhost:3000/api/enderecos
Content-Type: application/json

{   
    "cidade": 1,
    "nome": "Jardim Sorriso 1",
    "cep": "76300000",
    "numero": "85",
    "lagradouro": "Rua 26-B",
    "quadra": "G9",
    "pontoReferencia": null
}



###
PUT http://localhost:3000/api/enderecos/4
Content-Type: application/json

{   
    "cidade": 1,
    "nome": "Jardim Sorriso I",
    "cep": "76300000",
    "numero": "85",
    "lagradouro": "Rua 26-B",
    "quadra": "G9",
    "pontoReferencia": null
}